### ISSUE TITLE
error for gen_coll_list.py

### ISSUE THREAD

**Issue by BodhisattwaMandal** [prachatos/museums-of-india#7]
python3 gen_coll_list.py
Generating collections list from all-museums.csv
Traceback (most recent call last):
  File "gen_coll_list.py", line 27, in <module>
    count = gen_coll_from_csvlist(filename, indices)
  File "/home/admin/museums-of-india-master/_lib.py", line 158, in gen_coll_from_csvlist
    tot += (gen_coll_list(row["id"]))
  File "/home/admin/museums-of-india-master/_lib.py", line 22, in gen_coll_list
    text_json = json.loads(str(page.content.decode("utf-8")))
NameError: name 'json' is not defined

**Comment by prachatos** [comment]
Added json as import, will check for other issues.
