### ISSUE TITLE
error gen_coll_data.py

### ISSUE THREAD

**Issue by BodhisattwaMandal** [prachatos/museums-of-india#8]
python3 gen_coll_data.py
Generating data list from ngma_blr.csv
Traceback (most recent call last):
  File "gen_coll_data.py", line 31, in <module>
    count = gen_data_from_csvlist(filename, indices, nodesc)
TypeError: gen_data_from_csvlist() missing 3 required positional arguments: 'max_page', 'data', and 'image'

**Comment by prachatos** [comment]
Checking

**Comment by BodhisattwaMandal** [comment]
File "gen_coll_data.py", line 26
    except Exception:
         ^
SyntaxError: invalid syntax

**Comment by prachatos** [comment]
Fixed

**Comment by BodhisattwaMandal** [comment]
python3 gen_coll_data.py
Generating data list from ngma_blr.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gen_coll_data.py", line 54, in <module>
    image,
  File "/home/admin/museums-of-india-master/_lib.py", line 166, in gen_data_from_csvlist
    download_coll(csvlist.split(".")[0] + "-" + row[1], row[2], row[3], min_page, max_page, data, image)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 4381, in get_value
    return libindex.get_value_box(s, key)
  File "pandas/_libs/index.pyx", line 52, in pandas._libs.index.get_value_box
  File "pandas/_libs/index.pyx", line 48, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 113, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 104, in pandas._libs.util.validate_indexer
IndexError: index out of bounds

**Comment by prachatos** [comment]
Fixed
